"""initial routebridge schema

Revision ID: 6f7ec0865d57
Revises: 
Create Date: 2026-10-01 10:24:03.237097
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '6f7ec0865d57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('iso_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('default_currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('default_timezone', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_iso_code'), 'country', ['iso_code'], unique=True)
    op.create_table('tenant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('aggregate_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditevent_actor_id'), 'auditevent', ['actor_id'], unique=False)
    op.create_index(op.f('ix_auditevent_aggregate_id'), 'auditevent', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_auditevent_aggregate_type'), 'auditevent', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_auditevent_event_type'), 'auditevent', ['event_type'], unique=False)
    op.create_index(op.f('ix_auditevent_occurred_at'), 'auditevent', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_auditevent_tenant_id'), 'auditevent', ['tenant_id'], unique=False)
    op.create_table('customer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_phone'), 'customer', ['phone'], unique=False)
    op.create_index(op.f('ix_customer_tenant_id'), 'customer', ['tenant_id'], unique=False)
    op.create_table('driver',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('fleet_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_phone'), 'driver', ['phone'], unique=False)
    op.create_index(op.f('ix_driver_status'), 'driver', ['status'], unique=False)
    op.create_index(op.f('ix_driver_tenant_id'), 'driver', ['tenant_id'], unique=False)
    op.create_table('idempotencyrecord',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('request_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('response_json', sqlmodel.sql.sqltypes.AutoString(length=100000), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotencyrecord_key'), 'idempotencyrecord', ['key'], unique=False)
    op.create_index(op.f('ix_idempotencyrecord_tenant_id'), 'idempotencyrecord', ['tenant_id'], unique=False)
    op.create_table('merchant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('external_ref', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_tenant_id'), 'merchant', ['tenant_id'], unique=False)
    op.create_table('mobilesyncevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('aggregate_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('received_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobilesyncevent_aggregate_id'), 'mobilesyncevent', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_mobilesyncevent_device_id'), 'mobilesyncevent', ['device_id'], unique=False)
    op.create_index(op.f('ix_mobilesyncevent_event_id'), 'mobilesyncevent', ['event_id'], unique=False)
    op.create_index(op.f('ix_mobilesyncevent_event_type'), 'mobilesyncevent', ['event_type'], unique=False)
    op.create_index(op.f('ix_mobilesyncevent_tenant_id'), 'mobilesyncevent', ['tenant_id'], unique=False)
    op.create_table('operatingarea',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operatingarea_code'), 'operatingarea', ['code'], unique=False)
    op.create_index(op.f('ix_operatingarea_country_id'), 'operatingarea', ['country_id'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cod_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_customer_id'), 'order', ['customer_id'], unique=False)
    op.create_index(op.f('ix_order_external_ref'), 'order', ['external_ref'], unique=False)
    op.create_index(op.f('ix_order_merchant_id'), 'order', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    op.create_index(op.f('ix_order_tenant_id'), 'order', ['tenant_id'], unique=False)
    op.create_table('servicezone',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('operating_area_id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operating_area_id'], ['operatingarea.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicezone_code'), 'servicezone', ['code'], unique=False)
    op.create_index(op.f('ix_servicezone_operating_area_id'), 'servicezone', ['operating_area_id'], unique=False)
    op.create_index(op.f('ix_servicezone_tenant_id'), 'servicezone', ['tenant_id'], unique=False)
    op.create_table('tenantarea',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('operating_area_id', sa.Uuid(), nullable=False),
    sa.Column('local_currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['operating_area_id'], ['operatingarea.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenantarea_operating_area_id'), 'tenantarea', ['operating_area_id'], unique=False)
    op.create_index(op.f('ix_tenantarea_tenant_id'), 'tenantarea', ['tenant_id'], unique=False)
    op.create_table('deliveryjob',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveryjob_order_id'), 'deliveryjob', ['order_id'], unique=True)
    op.create_index(op.f('ix_deliveryjob_status'), 'deliveryjob', ['status'], unique=False)
    op.create_index(op.f('ix_deliveryjob_tenant_id'), 'deliveryjob', ['tenant_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('recipient', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('template', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('provider_message_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('sent_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_order_id'), 'notification', ['order_id'], unique=False)
    op.create_index(op.f('ix_notification_status'), 'notification', ['status'], unique=False)
    op.create_index(op.f('ix_notification_tenant_id'), 'notification', ['tenant_id'], unique=False)
    op.create_table('ratecard',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('service_zone_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cod_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_zone_id'], ['servicezone.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratecard_service_zone_id'), 'ratecard', ['service_zone_id'], unique=False)
    op.create_index(op.f('ix_ratecard_tenant_id'), 'ratecard', ['tenant_id'], unique=False)
    op.create_table('deliveryattempt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_job_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('reason_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('occurred_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_job_id'], ['deliveryjob.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveryattempt_delivery_job_id'), 'deliveryattempt', ['delivery_job_id'], unique=False)
    op.create_index(op.f('ix_deliveryattempt_tenant_id'), 'deliveryattempt', ['tenant_id'], unique=False)
    op.create_table('driverassignment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_job_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('assigned_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('unassigned_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_job_id'], ['deliveryjob.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driverassignment_delivery_job_id'), 'driverassignment', ['delivery_job_id'], unique=False)
    op.create_index(op.f('ix_driverassignment_driver_id'), 'driverassignment', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driverassignment_tenant_id'), 'driverassignment', ['tenant_id'], unique=False)
    op.create_table('paymentrecord',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_job_id', sa.Uuid(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('collected_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('provider_reference', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('reconciliation_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('recorded_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_job_id'], ['deliveryjob.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paymentrecord_delivery_job_id'), 'paymentrecord', ['delivery_job_id'], unique=False)
    op.create_index(op.f('ix_paymentrecord_order_id'), 'paymentrecord', ['order_id'], unique=False)
    op.create_index(op.f('ix_paymentrecord_provider_reference'), 'paymentrecord', ['provider_reference'], unique=False)
    op.create_index(op.f('ix_paymentrecord_reconciliation_status'), 'paymentrecord', ['reconciliation_status'], unique=False)
    op.create_index(op.f('ix_paymentrecord_tenant_id'), 'paymentrecord', ['tenant_id'], unique=False)
    op.create_table('stop',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_job_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('address_text', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('landmark', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('delivery_notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_confidence', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('recipient_available', sa.Boolean(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_job_id'], ['deliveryjob.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stop_delivery_job_id'), 'stop', ['delivery_job_id'], unique=False)
    op.create_index(op.f('ix_stop_status'), 'stop', ['status'], unique=False)
    op.create_index(op.f('ix_stop_tenant_id'), 'stop', ['tenant_id'], unique=False)
    op.create_table('proofofdelivery',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_job_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('otp_verified', sa.Boolean(), nullable=False),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('signature_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('recipient_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('captured_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['deliveryattempt.id'], ),
    sa.ForeignKeyConstraint(['delivery_job_id'], ['deliveryjob.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proofofdelivery_attempt_id'), 'proofofdelivery', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_proofofdelivery_delivery_job_id'), 'proofofdelivery', ['delivery_job_id'], unique=False)
    op.create_index(op.f('ix_proofofdelivery_tenant_id'), 'proofofdelivery', ['tenant_id'], unique=False)
    op.create_table('reconciliationitem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('variance_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('resolution_note', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['paymentrecord.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliationitem_payment_id'), 'reconciliationitem', ['payment_id'], unique=False)
    op.create_index(op.f('ix_reconciliationitem_tenant_id'), 'reconciliationitem', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliationitem_tenant_id'), table_name='reconciliationitem')
    op.drop_index(op.f('ix_reconciliationitem_payment_id'), table_name='reconciliationitem')
    op.drop_table('reconciliationitem')
    op.drop_index(op.f('ix_proofofdelivery_tenant_id'), table_name='proofofdelivery')
    op.drop_index(op.f('ix_proofofdelivery_delivery_job_id'), table_name='proofofdelivery')
    op.drop_index(op.f('ix_proofofdelivery_attempt_id'), table_name='proofofdelivery')
    op.drop_table('proofofdelivery')
    op.drop_index(op.f('ix_stop_tenant_id'), table_name='stop')
    op.drop_index(op.f('ix_stop_status'), table_name='stop')
    op.drop_index(op.f('ix_stop_delivery_job_id'), table_name='stop')
    op.drop_table('stop')
    op.drop_index(op.f('ix_paymentrecord_tenant_id'), table_name='paymentrecord')
    op.drop_index(op.f('ix_paymentrecord_reconciliation_status'), table_name='paymentrecord')
    op.drop_index(op.f('ix_paymentrecord_provider_reference'), table_name='paymentrecord')
    op.drop_index(op.f('ix_paymentrecord_order_id'), table_name='paymentrecord')
    op.drop_index(op.f('ix_paymentrecord_delivery_job_id'), table_name='paymentrecord')
    op.drop_table('paymentrecord')
    op.drop_index(op.f('ix_driverassignment_tenant_id'), table_name='driverassignment')
    op.drop_index(op.f('ix_driverassignment_driver_id'), table_name='driverassignment')
    op.drop_index(op.f('ix_driverassignment_delivery_job_id'), table_name='driverassignment')
    op.drop_table('driverassignment')
    op.drop_index(op.f('ix_deliveryattempt_tenant_id'), table_name='deliveryattempt')
    op.drop_index(op.f('ix_deliveryattempt_delivery_job_id'), table_name='deliveryattempt')
    op.drop_table('deliveryattempt')
    op.drop_index(op.f('ix_ratecard_tenant_id'), table_name='ratecard')
    op.drop_index(op.f('ix_ratecard_service_zone_id'), table_name='ratecard')
    op.drop_table('ratecard')
    op.drop_index(op.f('ix_notification_tenant_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_status'), table_name='notification')
    op.drop_index(op.f('ix_notification_order_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_deliveryjob_tenant_id'), table_name='deliveryjob')
    op.drop_index(op.f('ix_deliveryjob_status'), table_name='deliveryjob')
    op.drop_index(op.f('ix_deliveryjob_order_id'), table_name='deliveryjob')
    op.drop_table('deliveryjob')
    op.drop_index(op.f('ix_tenantarea_tenant_id'), table_name='tenantarea')
    op.drop_index(op.f('ix_tenantarea_operating_area_id'), table_name='tenantarea')
    op.drop_table('tenantarea')
    op.drop_index(op.f('ix_servicezone_tenant_id'), table_name='servicezone')
    op.drop_index(op.f('ix_servicezone_operating_area_id'), table_name='servicezone')
    op.drop_index(op.f('ix_servicezone_code'), table_name='servicezone')
    op.drop_table('servicezone')
    op.drop_index(op.f('ix_order_tenant_id'), table_name='order')
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_index(op.f('ix_order_merchant_id'), table_name='order')
    op.drop_index(op.f('ix_order_external_ref'), table_name='order')
    op.drop_index(op.f('ix_order_customer_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_operatingarea_country_id'), table_name='operatingarea')
    op.drop_index(op.f('ix_operatingarea_code'), table_name='operatingarea')
    op.drop_table('operatingarea')
    op.drop_index(op.f('ix_mobilesyncevent_tenant_id'), table_name='mobilesyncevent')
    op.drop_index(op.f('ix_mobilesyncevent_event_type'), table_name='mobilesyncevent')
    op.drop_index(op.f('ix_mobilesyncevent_event_id'), table_name='mobilesyncevent')
    op.drop_index(op.f('ix_mobilesyncevent_device_id'), table_name='mobilesyncevent')
    op.drop_index(op.f('ix_mobilesyncevent_aggregate_id'), table_name='mobilesyncevent')
    op.drop_table('mobilesyncevent')
    op.drop_index(op.f('ix_merchant_tenant_id'), table_name='merchant')
    op.drop_table('merchant')
    op.drop_index(op.f('ix_idempotencyrecord_tenant_id'), table_name='idempotencyrecord')
    op.drop_index(op.f('ix_idempotencyrecord_key'), table_name='idempotencyrecord')
    op.drop_table('idempotencyrecord')
    op.drop_index(op.f('ix_driver_tenant_id'), table_name='driver')
    op.drop_index(op.f('ix_driver_status'), table_name='driver')
    op.drop_index(op.f('ix_driver_phone'), table_name='driver')
    op.drop_table('driver')
    op.drop_index(op.f('ix_customer_tenant_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_phone'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_auditevent_tenant_id'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_occurred_at'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_event_type'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_aggregate_type'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_aggregate_id'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_actor_id'), table_name='auditevent')
    op.drop_table('auditevent')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_country_iso_code'), table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###
